//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: signal_fuse_protocol_buffers.proto
namespace com.signalfuse.metrics.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Datum")]
  public partial class Datum : global::ProtoBuf.IExtensible
  {
    public Datum() {}
    
    private string _strValue;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"strValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string strValue
    {
      get { return _strValue?? ""; }
      set { _strValue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool strValueSpecified
    {
      get { return this._strValue != null; }
      set { if (value == (this._strValue== null)) this._strValue = value ? this.strValue : (string)null; }
    }
    private bool ShouldSerializestrValue() { return strValueSpecified; }
    private void ResetstrValue() { strValueSpecified = false; }
    
    private double? _doubleValue;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"doubleValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double doubleValue
    {
      get { return _doubleValue?? default(double); }
      set { _doubleValue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool doubleValueSpecified
    {
      get { return this._doubleValue != null; }
      set { if (value == (this._doubleValue== null)) this._doubleValue = value ? this.doubleValue : (double?)null; }
    }
    private bool ShouldSerializedoubleValue() { return doubleValueSpecified; }
    private void ResetdoubleValue() { doubleValueSpecified = false; }
    
    private long? _intValue;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"intValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long intValue
    {
      get { return _intValue?? default(long); }
      set { _intValue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool intValueSpecified
    {
      get { return this._intValue != null; }
      set { if (value == (this._intValue== null)) this._intValue = value ? this.intValue : (long?)null; }
    }
    private bool ShouldSerializeintValue() { return intValueSpecified; }
    private void ResetintValue() { intValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Dimension")]
  public partial class Dimension : global::ProtoBuf.IExtensible
  {
    public Dimension() {}
    
    private string _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key?? ""; }
      set { _key = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool keySpecified
    {
      get { return this._key != null; }
      set { if (value == (this._key== null)) this._key = value ? this.key : (string)null; }
    }
    private bool ShouldSerializekey() { return keySpecified; }
    private void Resetkey() { keySpecified = false; }
    
    private string _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string value
    {
      get { return _value?? ""; }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool valueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.value : (string)null; }
    }
    private bool ShouldSerializevalue() { return valueSpecified; }
    private void Resetvalue() { valueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DataPoint")]
  public partial class DataPoint : global::ProtoBuf.IExtensible
  {
    public DataPoint() {}
    
    private string _source;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"source", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string source
    {
      get { return _source?? ""; }
      set { _source = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sourceSpecified
    {
      get { return this._source != null; }
      set { if (value == (this._source== null)) this._source = value ? this.source : (string)null; }
    }
    private bool ShouldSerializesource() { return sourceSpecified; }
    private void Resetsource() { sourceSpecified = false; }
    
    private string _metric;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"metric", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string metric
    {
      get { return _metric?? ""; }
      set { _metric = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool metricSpecified
    {
      get { return this._metric != null; }
      set { if (value == (this._metric== null)) this._metric = value ? this.metric : (string)null; }
    }
    private bool ShouldSerializemetric() { return metricSpecified; }
    private void Resetmetric() { metricSpecified = false; }
    
    private long? _timestamp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp?? default(long); }
      set { _timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timestampSpecified
    {
      get { return this._timestamp != null; }
      set { if (value == (this._timestamp== null)) this._timestamp = value ? this.timestamp : (long?)null; }
    }
    private bool ShouldSerializetimestamp() { return timestampSpecified; }
    private void Resettimestamp() { timestampSpecified = false; }
    
    private com.signalfuse.metrics.protobuf.Datum _value = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.signalfuse.metrics.protobuf.Datum value
    {
      get { return _value; }
      set { _value = value; }
    }
    private com.signalfuse.metrics.protobuf.MetricType? _metricType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"metricType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.signalfuse.metrics.protobuf.MetricType metricType
    {
      get { return _metricType?? com.signalfuse.metrics.protobuf.MetricType.GAUGE; }
      set { _metricType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool metricTypeSpecified
    {
      get { return this._metricType != null; }
      set { if (value == (this._metricType== null)) this._metricType = value ? this.metricType : (com.signalfuse.metrics.protobuf.MetricType?)null; }
    }
    private bool ShouldSerializemetricType() { return metricTypeSpecified; }
    private void ResetmetricType() { metricTypeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<com.signalfuse.metrics.protobuf.Dimension> _dimensions = new global::System.Collections.Generic.List<com.signalfuse.metrics.protobuf.Dimension>();
    [global::ProtoBuf.ProtoMember(6, Name=@"dimensions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.signalfuse.metrics.protobuf.Dimension> dimensions
    {
      get { return _dimensions; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DataPointUploadMessage")]
  public partial class DataPointUploadMessage : global::ProtoBuf.IExtensible
  {
    public DataPointUploadMessage() {}
    
    private readonly global::System.Collections.Generic.List<com.signalfuse.metrics.protobuf.DataPoint> _datapoints = new global::System.Collections.Generic.List<com.signalfuse.metrics.protobuf.DataPoint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"datapoints", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.signalfuse.metrics.protobuf.DataPoint> datapoints
    {
      get { return _datapoints; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PointValue")]
  public partial class PointValue : global::ProtoBuf.IExtensible
  {
    public PointValue() {}
    
    private long? _timestamp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp?? default(long); }
      set { _timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timestampSpecified
    {
      get { return this._timestamp != null; }
      set { if (value == (this._timestamp== null)) this._timestamp = value ? this.timestamp : (long?)null; }
    }
    private bool ShouldSerializetimestamp() { return timestampSpecified; }
    private void Resettimestamp() { timestampSpecified = false; }
    
    private com.signalfuse.metrics.protobuf.Datum _value = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.signalfuse.metrics.protobuf.Datum value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MetricType")]
    public enum MetricType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAUGE", Value=0)]
      GAUGE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COUNTER", Value=1)]
      COUNTER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENUM", Value=2)]
      ENUM = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CUMULATIVE_COUNTER", Value=3)]
      CUMULATIVE_COUNTER = 3
    }
  
}